name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
  release:
    runs-on: ubuntu-latest
    name: Release core package to webserver
    needs: call-test
    steps:
      - name: Install dependencies of envsubst
        run: sudo apt update && sudo apt install gettext-base

      - uses: actions/checkout@v3

      - run: mkdir output

      - uses: actions/download-artifact@v3
        with:
          name: core_zip
          path: output/Riotee_ArduinoCore_${RELEASE_VERSION}.zip

      - uses: actions/download-artifact@v3
        with:
          name: zip_props

      - name: Load zip properties into environment variables
        run: cat zip_props.env >> $GITHUB_ENV

      - name: Store release tag in environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
  
      - name: Render template of package_index snippet for release
        run: envsubst < package_index_snippet.tmpl > output/package_index_snippet.json

      - name: Upload zipped core as artifact
        uses: actions/upload-artifact@v3
        with:
          name: package_index_snippet
          path: output/package_index_snippet.json

      - name: Upload artifacts to webserver
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: www.riotee.nessie-circuits.de
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: output/
          server-dir: /htdocs/riotee/arduino/release/
          protocol: ftps