name: Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - RioteeBoard
    runs-on: ubuntu-latest
    name: Compile ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create blinky sketch to compile
        run: |
          mkdir blinky
          cat > blinky/blinky.ino << EOF
            void setup() {
              pinMode(LED_BUILTIN, OUTPUT);
            }

            void loop() {
              digitalWrite(LED_BUILTIN, HIGH);
              delay(1000);
              digitalWrite(LED_BUILTIN, LOW);
              delay(1000);
            }
          EOF

      - name: Populate core from external sources
        run: ./build_tree.sh

      - uses: arduino/compile-sketches@v1
        with:
          cli-version: latest
          verbose: true
          platforms: |
            # Install previous version from package index to get the tools
            - name: "riotee:riotee"
              source-url: "https://riotee.nessie-circuits.de/arduino/package_index.json"
              version: latest
            # Install current core from source
            - name: "riotee:riotee"
              source-path: .
          fqbn: "riotee:riotee:${{ matrix.variant }}"
          sketch-paths: blinky
